# IzgoN - one-shot setup for Windows.
#
# Double-click IzgoN-Setup.cmd, or run this directly:
#     powershell -ExecutionPolicy Bypass -File install-windows.ps1
#
# What it does, in order, and nothing else:
#   1. checks that Docker is installed and running
#   2. creates %USERPROFILE%\IzgoN
#   3. writes a compose file that pulls the published image - no build
#   4. generates a random API key and writes it to .env
#   5. starts IzgoN and Redis, waits until the health check passes
#   6. opens the dashboard
#
# It installs nothing into Windows itself and touches nothing outside that one
# folder. To remove IzgoN completely: run "docker compose down -v" in it, then
# delete the folder.

$ErrorActionPreference = "Stop"

function Say([string]$Text, [string]$Colour = "Gray") {
    Write-Host $Text -ForegroundColor $Colour
}

Say ""
Say "  IzgoN - setup" "Cyan"
Say "  ---------------------------------------------" "DarkGray"
Say ""

# --- 1. Docker ---------------------------------------------------------------
Say "  [1/5] Checking Docker..."
$docker = Get-Command docker -ErrorAction SilentlyContinue
if (-not $docker) {
    Say ""
    Say "  Docker is not installed." "Yellow"
    Say ""
    Say "  IzgoN is a server, and it needs Redis next to it. Docker is what runs"
    Say "  both with one command. Install it, restart the computer, then run this"
    Say "  again:"
    Say ""
    Say "      winget install -e --id Docker.DockerDesktop" "White"
    Say ""
    Read-Host "  Press Enter to close"
    exit 1
}

try {
    docker info 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "engine down" }
} catch {
    Say ""
    Say "  Docker is installed but not running." "Yellow"
    Say "  Start Docker Desktop, wait for 'Engine running', then run this again."
    Say ""
    Read-Host "  Press Enter to close"
    exit 1
}
Say "        Docker is running." "Green"

# --- 2. Folder ---------------------------------------------------------------
$Home_ = [Environment]::GetFolderPath("UserProfile")
$Dir = Join-Path $Home_ "IzgoN"
Say "  [2/5] Folder: $Dir"
New-Item -ItemType Directory -Force -Path $Dir | Out-Null
Set-Location $Dir

# --- 3. Compose file ---------------------------------------------------------
Say "  [3/5] Writing docker-compose.yml (pulls the published image, no build)..."
$Compose = @'
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  izgon:
    image: ghcr.io/izgamber/izgon:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      DATAPULSE_REDIS_URL: redis://redis:6379/0
      DATAPULSE_DB_PATH: /data/datapulse_events.db
      DATAPULSE_API_KEY: ${DATAPULSE_API_KEY}
      DATAPULSE_FREE_TIER_LIMIT: ${DATAPULSE_FREE_TIER_LIMIT:-10000}
      DATAPULSE_LICENSE_KEY: ${DATAPULSE_LICENSE_KEY:-}
      DATAPULSE_LICENSE_SECRET: ${DATAPULSE_LICENSE_SECRET:-}
      DATAPULSE_ALLOWED_ORIGINS: ${DATAPULSE_ALLOWED_ORIGINS:-*}
    volumes:
      - izgon-data:/data
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data:
  izgon-data:
'@
Set-Content -Path (Join-Path $Dir "docker-compose.yml") -Value $Compose -Encoding UTF8

# --- 4. API key --------------------------------------------------------------
$EnvPath = Join-Path $Dir ".env"
if (Test-Path $EnvPath) {
    Say "  [4/5] .env already exists - keeping your existing key." "Yellow"
    $hit = Select-String -Path $EnvPath -Pattern '^DATAPULSE_API_KEY=(.*)$' | Select-Object -First 1
    if ($hit) { $Key = $hit.Matches[0].Groups[1].Value } else { $Key = "(see .env)" }
} else {
    Say "  [4/5] Generating an API key..."
    $bytes = New-Object byte[] 24
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $rng.GetBytes($bytes)
    $Key = [Convert]::ToBase64String($bytes).Replace('+','-').Replace('/','_').TrimEnd('=')
    $EnvBody = @(
        "# Generated by install-windows.ps1. Keep this file out of git.",
        "DATAPULSE_API_KEY=$Key",
        "DATAPULSE_FREE_TIER_LIMIT=10000",
        "DATAPULSE_ALLOWED_ORIGINS=*",
        "DATAPULSE_LICENSE_KEY=",
        "DATAPULSE_LICENSE_SECRET="
    )
    Set-Content -Path $EnvPath -Value $EnvBody -Encoding UTF8
}

# --- 5. Start ----------------------------------------------------------------
Say "  [5/5] Pulling the image and starting (first run takes a minute)..."
docker compose up -d
if ($LASTEXITCODE -ne 0) {
    Say ""
    Say "  docker compose failed. The output above says why." "Red"
    Read-Host "  Press Enter to close"
    exit 1
}

Say "        Waiting for the service to answer..."
$up = $false
foreach ($i in 1..60) {
    Start-Sleep -Seconds 2
    try {
        $r = Invoke-WebRequest -Uri "http://localhost:8000/healthz" -TimeoutSec 3 -UseBasicParsing
        if ($r.StatusCode -eq 200) { $up = $true; break }
    } catch { }
}

Say ""
if ($up) {
    Say "  ---------------------------------------------" "DarkGray"
    Say "  IzgoN is running." "Green"
    Say ""
    Say "  Dashboard:  http://localhost:8000" "White"
    Say "  API key:    $Key" "White"
    Say "  Folder:     $Dir"
    Say ""
    Say "  Send your first report - paste this into PowerShell:" "DarkGray"
    $example = @"

      `$h = @{ 'X-API-Key' = '$Key' }
      Invoke-RestMethod -Uri http://localhost:8000/api/nodes/sensor-01/sync ``
        -Method Post -ContentType 'application/json' -Headers `$h ``
        -Body '{"state": {"temp": 21.5, "hum": 60}}'

  Send it twice. The second time comes back NO_CHANGE, 0 bytes.
"@
    Write-Host $example -ForegroundColor DarkGray
    Say ""
    Say "  Stop it:    docker compose down      (in $Dir)" "DarkGray"
    Say "  Remove it:  docker compose down -v   (also deletes the data)" "DarkGray"
    Say "  ---------------------------------------------" "DarkGray"
    Start-Process "http://localhost:8000"
} else {
    Say "  Started, but nothing answered on http://localhost:8000 in two minutes." "Yellow"
    Say "  Check what the containers say:" "Yellow"
    Say ""
    Say "      docker compose ps" "White"
    Say "      docker compose logs izgon" "White"
    Say ""
    Say "  Folder: $Dir"
}

Say ""
Read-Host "  Press Enter to close"
